package org.volodymyrzganiaiko.gym.crm.system.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@ApiModel(description = "Details required to register a trainer. Username and password are generated by the server.")
public record TrainerRegistrationRequest(
        @ApiModelProperty(value = "First name of the trainer", required = true, example = "Jane")
        @NotBlank String firstName,

        @ApiModelProperty(value = "Last name of the trainer", required = true, example = "Roe")
        @NotBlank String lastName,

        @ApiModelProperty(value = "Identifier of an existing training type the trainer specializes in", required = true, example = "2")
        @NotNull Long specializationId) {
}