package org.volodymyrzganiaiko.gym.crm.system.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotBlank;
import java.time.LocalDate;

@ApiModel(description = "Details required to register a trainee. Username and password are generated by the server.")
public record TraineeRegistrationRequest(
        @ApiModelProperty(value = "First name of the trainee", required = true, example = "John")
        @NotBlank String firstName,

        @ApiModelProperty(value = "Last name of the trainee", required = true, example = "Doe")
        @NotBlank String lastName,

        @ApiModelProperty(value = "Date of birth, optional", example = "1990-05-15")
        LocalDate dateOfBirth,

        @ApiModelProperty(value = "Postal address, optional", example = "Main st. 1")
        String address) {
}